meta:
  role: repository_index
  version: 1.0
  status: draft

stages:
  - stage: "0_source"
    id: 0
    docs:
      - id: "0-1"
        path: "00_docs/0_source/0-1_source_origin.yaml"
        depends_on: []
      - id: "0-2"
        path: "00_docs/0_source/0-2_world_rules.yaml"
        depends_on: []
      - id: "0-3"
        path: "00_docs/0_source/0-3_assets_entities.yaml"
        depends_on: []
      - id: "0-4"
        path: "00_docs/0_source/0-4_visual_direction.yaml"
        depends_on: []
      - id: "0-5"
        path: "00_docs/0_source/0-5_references_constraints.yaml"
        depends_on: []

  - stage: "1_story"
    id: 1
    docs:
      - id: "1-1"
        path: "00_docs/1_story/1-1_script_text.yaml"
        depends_on: ["0-1"]
      - id: "1-2"
        path: "00_docs/1_story/1-2_segment_structure.yaml"
        depends_on: ["1-1", "0-2", "0-3"]
      - id: "1-3"
        path: "00_docs/1_story/1-3_segment_drama.yaml"
        depends_on: ["1-2", "0-2", "0-3"]
      - id: "1-3a"
        path: "00_docs/1_story/1-3a_segment_story_test.yaml"
        depends_on: ["1-2", "1-3", "0-2", "0-3", "X-1", "X-4", "X-5"]
      - id: "1-4"
        path: "00_docs/1_story/1-4_shot_narrative.yaml"
        depends_on: ["1-3a", "X-6"]
      - id: "1-5"
        path: "00_docs/1_story/1-5_shot_list.yaml"
        depends_on: ["1-4", "X-6", "X-7"]

  - stage: "2_layout"
    id: 2
    docs:
      - id: "2-1"
        path: "00_docs/2_layout/2-1_cinematic_intent.yaml"
        depends_on: ["1-5", "1-4", "X-6"]
      - id: "2-2"
        path: "00_docs/2_layout/2-2_layout_freeze.yaml"
        depends_on: ["2-1", "1-5", "X-2", "X-4", "X-7"]

  - stage: "3_lookdev"
    id: 3
    docs:
      - id: "3-1"
        path: "00_docs/3_lookdev/3-1_lookdev.yaml"
        depends_on: ["0-4", "2-2", "X-3", "X-4", "X-5"]

  - stage: "4_production"
    id: 4
    docs:
      - id: "4-1"
        path: "00_docs/4_production/4-1_shot_production.yaml"
        depends_on: ["2-2", "3-1", "X-4", "X-5"]
      - id: "4-2"
        path: "00_docs/4_production/4-2_post_production.yaml"
        depends_on: ["4-1", "X-5", "X-6"]

shared_exec_inputs:
  - id: "X-4"
    path: "00_docs/X_exec/X-4_prompt_input.yaml"
    role: "prompt_input"
  - id: "X-5"
    path: "00_docs/X_exec/X-5_token_input.yaml"
    role: "token_input"
  - id: "X-6"
    path: "00_docs/X_exec/X-6_srt_input.yaml"
    role: "srt_input"
  - id: "X-7"
    path: "00_docs/X_exec/X-7_xml_input.yaml"
    role: "xml_input"
