meta:
  role: repository_index
  version: 1.0
  status: draft

stages:
  - stage: "0_source"
    id: 0
    docs:
      - id: "0-1"
        path: "30_project/docs/0-source/raw/structured/0-1_source_origin.yaml"
        depends_on: []
      - id: "0-2"
        path: "30_project/docs/0-source/raw/structured/0-2_world_rules.yaml"
        depends_on: []
      - id: "0-3"
        path: "30_project/docs/0-source/raw/structured/0-3_assets_entities.yaml"
        depends_on: []
      - id: "0-4"
        path: "30_project/docs/0-source/raw/structured/0-4_visual_direction.yaml"
        depends_on: []
      - id: "0-5"
        path: "30_project/docs/0-source/raw/structured/0-5_references_constraints.yaml"
        depends_on: []

  - stage: "1_story"
    id: 1
    docs:
      - id: "1-1"
        path: "30_project/docs/1_story/script_breakdown_v1.yaml"
        depends_on: ["0-1"]
      - id: "1-2"
        path: "30_project/docs/1_story/1-2_segment_structure.yaml"
        depends_on: ["1-1"]

  - stage: "2_layout"
    id: 2
    docs:
      - id: "2-1"
        path: "30_project/docs/2_layout/_artifacts/inputs/2-1_cinematic_intent_v1.yaml"
        depends_on: ["1-1", "1-2"]
      - id: "2-2"
        path: "30_project/docs/2_layout/2-2_layout_freeze.yaml"
        depends_on: ["2-1", "1-1"]

  - stage: "2_audio"
    id: 3
    docs:
      - id: "2A-1"
        path: "30_project/docs/2_audio/_artifacts/audio_plan_v1.yaml"
        depends_on: ["2-1"]
      - id: "2A-2"
        path: "30_project/docs/2_audio/_artifacts/prompt_packs/dialogue_vo_prompt_pack_v1.yaml"
        depends_on: ["2A-1"]
      - id: "2A-3"
        path: "30_project/docs/2_audio/_artifacts/reports/audio_review_v1.md"
        depends_on: ["2A-2"]

  - stage: "5_color"
    id: 4
    docs:
      - id: "5-1"
        path: "30_project/docs/5_color/_artifacts/reports/color_qc_v1.md"
        depends_on: ["2A-3"]
      - id: "5-2"
        path: "30_project/docs/5_color/_artifacts/reports/color_review_v1.md"
        depends_on: ["5-1"]

shared_exec_inputs:
  - id: "X-4"
    path: "90_archive/docs/X_exec/X-4_prompt_input.yaml"
    role: "prompt_input"
  - id: "X-5"
    path: "90_archive/docs/X_exec/X-5_token_input.yaml"
    role: "token_input"
