stages:
  - name: "Stage S"
    description: "Source Synthesis / script confirmation"
    product: "30_project/inputs/script/source_script.md"
    approval_key: "SOURCE_SCRIPT_APPROVED"
    requires: []
    next_targets: ["Stage B"]
  - name: "Stage B"
    description: "Script breakdown (first draft)"
    product: "30_project/docs/1_story/script_breakdown_v1.yaml"
    approval_key: "SCRIPT_BREAKDOWN_APPROVED"
    requires:
      - "SOURCE_SCRIPT_APPROVED"
    next_targets: ["Stage C", "Stage A1"]
  - name: "Stage C"
    description: "Human creative/production decisions"
    product: "00_human/DECISIONS.md"
    approval_key: "STAGE_C_DECISION_APPROVED"
    requires:
      - "SCRIPT_BREAKDOWN_APPROVED"
    next_targets: ["Stage D"]
  - name: "Stage A1"
    description: "Audio plan"
    product: "30_project/docs/2_audio/_artifacts/audio_plan_v1.yaml"
    approval_key: "AUDIO_PLAN_APPROVED"
    requires:
      - "SCRIPT_BREAKDOWN_APPROVED"
    next_targets: ["Stage A2"]
  - name: "Stage A2"
    description: "Audio prompt packs"
    product: "30_project/docs/2_audio/_artifacts/prompt_packs/dialogue_vo_prompt_pack_v1.yaml + 30_project/docs/2_audio/_artifacts/prompt_packs/sfx_prompt_pack_v1.yaml + 30_project/docs/2_audio/_artifacts/prompt_packs/music_prompt_pack_v1.yaml"
    approval_key: "AUDIO_PROMPTS_APPROVED"
    requires:
      - "AUDIO_PLAN_APPROVED"
    next_targets: ["Stage A3"]
  - name: "Stage A3"
    description: "Audio review"
    product: "30_project/docs/2_audio/_artifacts/reports/audio_review_v1.md"
    approval_key: "AUDIO_REVIEW_APPROVED"
    requires:
      - "AUDIO_PROMPTS_APPROVED"
    next_targets: []
  - name: "Stage D"
    description: "Cinematic intent / layout guidance"
    product: "30_project/docs/2_layout/_artifacts/2-1_cinematic_intent_v1.yaml"
    approval_key: "CINEMATIC_INTENT_APPROVED"
    requires:
      - "STAGE_C_DECISION_APPROVED"
    next_targets: ["Stage P1.5"]
  - name: "Stage P1.5"
    description: "Shot map SRT for downstream mapping"
    product: "30_project/docs/2_layout/_artifacts/editing_bridge/shot_map_v1.srt + 30_project/docs/2_layout/_artifacts/editing_bridge/timeline_plan_v1.xml"
    approval_key: "SHOT_MAP_SRT_XML_APPROVED"
    requires:
      - "CINEMATIC_INTENT_APPROVED"
    next_targets: ["Stage E"]
  - name: "Stage E"
    description: "Layout freeze"
    product: "30_project/docs/2_layout/2-2_layout_freeze.yaml"
    approval_key: "LAYOUT_FREEZE_APPROVED"
    requires:
      - "SHOT_MAP_SRT_XML_APPROVED"
    next_targets: ["Stage LR"]
  - name: "Stage LR"
    description: "Layout review and acceptance"
    product: "30_project/docs/2_layout/_artifacts/reports/layout_review_v1.md"
    approval_key: "LAYOUT_REVIEW_APPROVED"
    requires:
      - "LAYOUT_FREEZE_APPROVED"
    next_targets: ["Stage K"]
  - name: "Stage K"
    description: "Lookdev shot prompts"
    product: "30_project/docs/2_layout/_artifacts/branch_lookdev_shot_prompt_pack_v1.yaml"
    approval_key: "LOOKDEV_PROMPTS_APPROVED"
    requires:
      - "LAYOUT_REVIEW_APPROVED"
      - "CINEMATIC_INTENT_APPROVED"
    next_targets: ["Stage K_R"]
  - name: "Stage K_R"
    description: "Lookdev review (must cover STANDARDS_LOOKDEV.md pillars)"
    product: "30_project/docs/2_layout/_artifacts/reports/lookdev_review_v1.md"
    approval_key: "LOOKDEV_REVIEW_APPROVED"
    requires:
      - "LOOKDEV_PROMPTS_APPROVED"
    next_targets: ["Stage F"]
  - name: "Stage F"
    description: "Execution planning"
    product: "20_runtime/exec/execution_plan.json"
    approval_key: "EXEC_PLAN_APPROVED"
    requires:
      - "LAYOUT_FREEZE_APPROVED"
      - "LOOKDEV_PROMPTS_APPROVED"
      - "LOOKDEV_REVIEW_APPROVED"
    next_targets: []
